import StyledComponentsRegistry from "@/style/lib/registry";
import Theme from "@/style/lib/theme";
import type { Metadata } from "next";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Script
          src="https://www.youtube.com/iframe_api"
          strategy="beforeInteractive"
        />
        <StyledComponentsRegistry>
          <Theme>{children}</Theme>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
